package com.mudhut.software.kasisira.profiles.mappers

import com.mudhut.software.kasisira.profiles.entities.Contact
import com.mudhut.software.kasisira.profiles.models.request.CreateContactRequest
import com.mudhut.software.kasisira.profiles.models.response.ContactResponse
import org.springframework.stereotype.Component

@Component
class ContactMapper {

    fun toResponse(contact: Contact): ContactResponse {
        return ContactResponse(
            id = contact.id,
            phoneNumber = contact.phoneNumber,
            isPrimary = contact.isPrimary,
            isVerified = contact.isVerified,
            label = contact.label,
            createdAt = contact.createdAt,
            updatedAt = contact.updatedAt
        )
    }

    fun toResponseList(contacts: List<Contact>): List<ContactResponse> {
        return contacts.map { toResponse(it) }
    }

    fun fromCreateRequest(request: CreateContactRequest): Contact {
        return Contact(
            id = 0, // Will be generated by database
            phoneNumber = request.phoneNumber,
            isPrimary = request.isPrimary,
            isVerified = false,
            label = request.label
        )
    }
}
