package com.mudhut.software.kasisira.profiles.mappers

import com.mudhut.software.kasisira.profiles.entities.Contact
import com.mudhut.software.kasisira.profiles.entities.User
import com.mudhut.software.kasisira.profiles.models.request.RegisterRequest
import com.mudhut.software.kasisira.profiles.models.response.UserResponse
import com.mudhut.software.kasisira.profiles.repositories.UserRoleRepository
import org.springframework.stereotype.Component

@Component
class UserMapper(
    private val contactMapper: ContactMapper,
    private val userRoleRepository: UserRoleRepository
) {

    fun toResponse(user: User): UserResponse {
        // NOTE: this issues one query per mapped user. If a caller maps many users in a
        // loop (e.g. a future list-users endpoint that wires through findAllUsers()), this
        // becomes N+1. Today no such endpoint is wired, but if/when it is, switch to a
        // batched lookup (e.g. findAllByUserIdIn) and a pre-computed map of userId -> roles.
        val roles = userRoleRepository.findAllByUserId(user.id)
            .map { it.roleName.name }
            .toSet()

        return UserResponse(
            id = user.id,
            username = user.username,
            email = user.email,
            provider = user.provider,
            imageUrl = user.imageUrl,
            emailVerified = user.emailVerified,
            isActive = user.isActive,
            isEnabled = user.isEnabled,
            contacts = user.contacts.map { contactMapper.toResponse(it) },
            createdAt = user.createdAt,
            updatedAt = user.updatedAt,
            lastLogin = user.lastLogin,
            roles = roles
        )
    }

    fun toResponseList(users: List<User>): List<UserResponse> {
        return users.map { toResponse(it) }
    }

    fun fromRegisterRequest(request: RegisterRequest, encodedPassword: String): User {
        return User(
            id = 0, // Will be generated by database
            username = request.username,
            email = request.email,
            passwordHash = encodedPassword,
            provider = request.provider,
            providerId = request.providerId,
            imageUrl = request.imageUrl,
            emailVerified = false,
            isActive = false,
            isEnabled = true
        )
    }

    fun fromRegisterRequestWithContact(request: RegisterRequest, encodedPassword: String): User {
        val user = fromRegisterRequest(request, encodedPassword)

        // Add contact if phone number is provided
        if (!request.phoneNumber.isNullOrBlank()) {
            val contact = Contact(
                id = 0,
                phoneNumber = request.phoneNumber,
                isPrimary = true,
                isVerified = false,
                label = request.phoneLabel ?: "Primary"
            )
            user.addContact(contact)
        }

        return user
    }
}
